name: <SERVICE_NAME> Service CI/CD

on:
  push:
    branches: [main]
    paths:
      - "<SERVICE_DIR>/**"
      - "<K8S_BASE_PATH>/**"
      - "<MINIKUBE_OVERLAY_SERVICE_PATH>/**"
      - ".github/workflows/<SERVICE_NAME>.yaml"
  pull_request:
    branches: [main]
    paths:
      - "<SERVICE_DIR>/**"
      - "<K8S_BASE_PATH>/**"
      - "<MINIKUBE_OVERLAY_SERVICE_PATH>/**"
      - ".github/workflows/<SERVICE_NAME>.yaml"

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/<SERVICE_IMAGE_NAME>

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: <SERVICE_DIR>
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      # - name: Lint
      #   run: npm run lint

      - name: Test
        run: npm test

  sonarqube-analysis:
    name: SonarQube Analysis
    needs: build-and-test
    runs-on: [self-hosted]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node (for coverage tooling)
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install root dependencies (coverage helpers)
        run: npm ci
      - name: Generate coverage reports for services
        run: |
          set -e
          # Replace the loop contents with the actual services requiring coverage reports.
          for service in <SERVICE_DIR> <OTHER_SERVICE_DIRS>; do
            echo "Running coverage for $service"
            (cd "$service" && npm ci && npx vitest run --coverage --coverage.reporter=lcov)
          done
      - name: SonarQube Scan (LO4 automation, LO6 code quality/security)
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  build-and-push:
    needs: build-and-test
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker buildx build --push \
            -f <SERVICE_DOCKERFILE> \
            -t $IMAGE_NAME:latest \
            -t $IMAGE_NAME:${{ github.sha }} \
            <SERVICE_DIR>

  dependency-security-scan:
    name: Dependency Security Scan
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Audit dependencies (OWASP A06 - vulnerable components)
        run: |
          set -e
          echo "Auditing <SERVICE_NAME>"
          (cd "<SERVICE_DIR>" && npm ci && npm audit --audit-level=high)

  image-vulnerability-scan:
    name: Container Image Vulnerability Scan
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Scan built image with Trivy (OWASP A06 / LO6 Security assessment)
        uses: aquasecurity/trivy-action@0.33.0
        with:
          image-ref: ${{ env.IMAGE_NAME }}:${{ github.sha }}
          severity: HIGH,CRITICAL
          exit-code: '1'

  deploy-minikube:
    needs: [build-and-push, dependency-security-scan, image-vulnerability-scan]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: [self-hosted, minikube]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Apply <SERVICE_NAME> overlay
        run: minikube kubectl -- apply -k <MINIKUBE_OVERLAY_SERVICE_PATH>

      - name: Update image
        run: minikube kubectl -- set image deployment/<DEPLOYMENT_NAME> <CONTAINER_NAME>=$IMAGE_NAME:${{ github.sha }} -n default

      - name: Verify rollout
        run: minikube kubectl -- rollout status deployment/<DEPLOYMENT_NAME> --timeout=120s
